### ISSUE TITLE
Could '../data/eb_v4_df_pca200.npy' be shared?

### ISSUE THREAD

**Issue by XJTU-XGU** [KrishnaswamyLab/MIOFlow#5]
Dear authors, 

Thanks for the great paper and the codes. However, the processed data file of Embryoid Body,  '../data/eb_v4_df_pca200.npy' is missing. Could you share it? Looking forward to your reply. Thanks again.

Best.

**Comment by guillaumehu** [comment]
Apologies for the very late reply. I have added the file to a google drive [here](https://drive.google.com/file/d/1HvEUDO1U73iHmt-vY4YbTvOUxr6IdpK_/view?usp=drive_link).
